#ifndef _UPTP_H
#define _UPTP_H

//*************************************************************************** 
//*
//*  C++ bindings for UPTIGHT 
//*
//*  Generated by bind_fortran (DO NOT EDIT MANUALLY)
//*
//***************************************************************************
//* Notes:
//*   o) these bindings need the "fortran.h" header file
//*   o) you should call only the f77_* functions from C++ in order to make
//*      sure, that your code does not depend on the naming convention of
//*      the different compilers (e.g. trailing underscores)
//***************************************************************************

#include "fortran.h"

// Some defintions for constants used by Uptight
const int UPT_SC = 100;
const int UPT_MC = 200;
const int UPT_LC = 500;
const int UPT_HSIZE = 4;
const char UPT_PADCHAR = ' ';



extern "C" void upt_gethandlersize_ (f77_int&);

// Corresponding F77 arguments for f77_upt_gethandlersize:
// integer, intent(out) :: handlerSize
inline void f77_upt_gethandlersize (f77_int& handlerSize)
{
  upt_gethandlersize_ (handlerSize);
}


extern "C" void upt_initsession_ (f77_int*);

// Corresponding F77 arguments for f77_upt_initsession:
// integer, intent(out) :: handler(DAC_handlerSize)
inline void f77_upt_initsession (f77_int* handler)
{
  upt_initsession_ (handler);
}


extern "C" void upt_destructsession_ (f77_int*);

// Corresponding F77 arguments for f77_upt_destructsession:
// integer, intent(inout) :: handler(DAC_handlerSize)
inline void f77_upt_destructsession (f77_int* handler)
{
  upt_destructsession_ (handler);
}


extern "C" void upt_getversion_ (f77_int const*);

// Corresponding F77 arguments for f77_upt_getversion:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_upt_getversion (f77_int const* handler)
{
  upt_getversion_ (handler);
}


extern "C" void upt_setmpicomm_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_upt_setmpicomm:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: comm
inline void f77_upt_setmpicomm (f77_int const* handler, f77_int const& comm)
{
  upt_setmpicomm_ (handler, comm);
}


extern "C" void upt_set_paths_ (f77_int const*, f77_char const*, f77_char 
    const*, f77_char const*);

// Corresponding F77 arguments for f77_upt_set_paths:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: databasePath(1)
// character(LST), intent(in) :: workPath(1)
// character(LST), intent(in) :: outPath(1)
inline void f77_upt_set_paths (f77_int const* handler, f77_char const* 
    databasePath, f77_char const* workPath, f77_char const* outPath)
{
  upt_set_paths_ (handler, databasePath, workPath, outPath);
}


extern "C" void upt_fillbasicparameters_ (f77_int const*, f77_int const&, 
    f77_char const*, f77_char const*, f77_char const*, f77_int const&, f77_int 
    const&, f77_int const&, f77_int const&, f77_int const&, f77_int const&, 
    f77_double const&, f77_double const&, f77_double const&, f77_int const&, 
    f77_double const&, f77_double const&, f77_int const&);

// Corresponding F77 arguments for f77_upt_fillbasicparameters:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: verbose_lev
// character(MST), intent(in) :: gen_filename(1)
// character(MST), intent(in) :: gen_outname(1)
// character(MST), intent(in) :: sparse_fmt(1)
// integer, intent(in) :: max_n_n
// integer, intent(in) :: harrison_flag
// integer, intent(in) :: relat_flag
// integer, intent(in) :: potential_flag
// integer, intent(in) :: optmat_flag
// integer, intent(in) :: poldir
// real(dp), intent(in) :: c_axis_x
// real(dp), intent(in) :: c_axis_y
// real(dp), intent(in) :: c_axis_z
// integer, intent(in) :: check_bondmap
// real(dp), intent(in) :: dg_coupl_scale
// real(dp), intent(in) :: dg_onsite
// integer, intent(in) :: hybrid_passivation
inline void f77_upt_fillbasicparameters (f77_int const* handler, f77_int const& 
    verbose_lev, f77_char const* gen_filename, f77_char const* gen_outname, 
    f77_char const* sparse_fmt, f77_int const& max_n_n, f77_int const& 
    harrison_flag, f77_int const& relat_flag, f77_int const& potential_flag, 
    f77_int const& optmat_flag, f77_int const& poldir, f77_double const& 
    c_axis_x, f77_double const& c_axis_y, f77_double const& c_axis_z, f77_int 
    const& check_bondmap, f77_double const& dg_coupl_scale, f77_double const& 
    dg_onsite, f77_int const& hybrid_passivation)
{
  upt_fillbasicparameters_ (handler, verbose_lev, gen_filename, gen_outname, 
      sparse_fmt, max_n_n, harrison_flag, relat_flag, potential_flag, 
      optmat_flag, poldir, c_axis_x, c_axis_y, c_axis_z, check_bondmap, 
      dg_coupl_scale, dg_onsite, hybrid_passivation);
}


extern "C" void upt_setworkpath_ (f77_int const*, f77_char const*);

// Corresponding F77 arguments for f77_upt_setworkpath:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: workPath(1)
inline void f77_upt_setworkpath (f77_int const* handler, f77_char const* 
    workPath)
{
  upt_setworkpath_ (handler, workPath);
}


extern "C" void upt_setoutpath_ (f77_int const*, f77_char const*);

// Corresponding F77 arguments for f77_upt_setoutpath:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: outPath(1)
inline void f77_upt_setoutpath (f77_int const* handler, f77_char const* outPath)
{
  upt_setoutpath_ (handler, outPath);
}


extern "C" void upt_setloadpath_ (f77_int const*, f77_char const*);

// Corresponding F77 arguments for f77_upt_setloadpath:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: loadPath(1)
inline void f77_upt_setloadpath (f77_int const* handler, f77_char const* 
    loadPath)
{
  upt_setloadpath_ (handler, loadPath);
}


extern "C" void upt_setstatefile_ (f77_int const*, f77_char const*);

// Corresponding F77 arguments for f77_upt_setstatefile:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: filename(1)
inline void f77_upt_setstatefile (f77_int const* handler, f77_char const* 
    filename)
{
  upt_setstatefile_ (handler, filename);
}


extern "C" void upt_setoutput_ (f77_int const*, f77_int const&, f77_double 
    const&);

// Corresponding F77 arguments for f77_upt_setoutput:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: out_form
// real(dp), intent(in) :: step
inline void f77_upt_setoutput (f77_int const* handler, f77_int const& out_form, 
    f77_double const& step)
{
  upt_setoutput_ (handler, out_form, step);
}


extern "C" void upt_setpmatrix_ (f77_int const*, f77_int const&, f77_int 
    const&);

// Corresponding F77 arguments for f77_upt_setpmatrix:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: optmat_flag
// integer, intent(in) :: poldir
inline void f77_upt_setpmatrix (f77_int const* handler, f77_int const& 
    optmat_flag, f77_int const& poldir)
{
  upt_setpmatrix_ (handler, optmat_flag, poldir);
}


extern "C" void upt_inituptight_ (f77_int const*);

// Corresponding F77 arguments for f77_upt_inituptight:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_upt_inituptight (f77_int const* handler)
{
  upt_inituptight_ (handler);
}


extern "C" void upt_destructuptight_ (f77_int const*);

// Corresponding F77 arguments for f77_upt_destructuptight:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_upt_destructuptight (f77_int const* handler)
{
  upt_destructuptight_ (handler);
}


extern "C" void upt_addpotential_ (f77_int const*, f77_int const&, f77_double 
    const*);

// Corresponding F77 arguments for f77_upt_addpotential:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nAtoms
// real(dp), intent(in) :: potential(nAtoms)
inline void f77_upt_addpotential (f77_int const* handler, f77_int const& 
    nAtoms, f77_double const* potential)
{
  upt_addpotential_ (handler, nAtoms, potential);
}


extern "C" void upt_erasepotential_ (f77_int const*);

// Corresponding F77 arguments for f77_upt_erasepotential:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_upt_erasepotential (f77_int const* handler)
{
  upt_erasepotential_ (handler);
}


extern "C" void upt_createhamiltonian_ (f77_int const*, f77_char const*);

// Corresponding F77 arguments for f77_upt_createhamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(MST), intent(in) :: sparse_fmt(1)
inline void f77_upt_createhamiltonian (f77_int const* handler, f77_char const* 
    sparse_fmt)
{
  upt_createhamiltonian_ (handler, sparse_fmt);
}


extern "C" void upt_printhamiltonian_ (f77_int const*);

// Corresponding F77 arguments for f77_upt_printhamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_upt_printhamiltonian (f77_int const* handler)
{
  upt_printhamiltonian_ (handler);
}


extern "C" void upt_setkpoint_ (f77_int const*, f77_double const*);

// Corresponding F77 arguments for f77_upt_setkpoint:
// integer, intent(in) :: handler(DAC_handlerSize)
// real(dp), intent(in) :: k_vec(3)
inline void f77_upt_setkpoint (f77_int const* handler, f77_double const* k_vec)
{
  upt_setkpoint_ (handler, k_vec);
}


extern "C" void upt_lanczosdiag_ (f77_int const*, f77_int const&, f77_int 
    const&, f77_int const&, f77_int const&, f77_double const&, f77_double 
    const&, f77_int const&, f77_int const&, f77_int const&, f77_double const&, 
    f77_double const&, f77_double const&, f77_int const&, f77_double const&);

// Corresponding F77 arguments for f77_upt_lanczosdiag:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: st_vb
// integer, intent(in) :: st_cb
// integer, intent(in) :: n_vb
// integer, intent(in) :: n_cb
// real(dp), intent(in) :: guess_vb
// real(dp), intent(in) :: guess_cb
// integer, intent(in) :: min_iter
// integer, intent(in) :: long_iter
// integer, intent(in) :: max_iter
// real(dp), intent(in) :: fast_tol
// real(dp), intent(in) :: long_tol
// real(dp), intent(in) :: ort_tol
// integer, intent(in) :: dynamic
// real(dp), intent(in) :: bitoff
inline void f77_upt_lanczosdiag (f77_int const* handler, f77_int const& st_vb, 
    f77_int const& st_cb, f77_int const& n_vb, f77_int const& n_cb, f77_double 
    const& guess_vb, f77_double const& guess_cb, f77_int const& min_iter, 
    f77_int const& long_iter, f77_int const& max_iter, f77_double const& 
    fast_tol, f77_double const& long_tol, f77_double const& ort_tol, f77_int 
    const& dynamic, f77_double const& bitoff)
{
  upt_lanczosdiag_ (handler, st_vb, st_cb, n_vb, n_cb, guess_vb, guess_cb, 
      min_iter, long_iter, max_iter, fast_tol, long_tol, ort_tol, dynamic, 
      bitoff);
}


extern "C" void upt_solver_flag_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_upt_solver_flag:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: flag
inline void f77_upt_solver_flag (f77_int const* handler, f77_int const& flag)
{
  upt_solver_flag_ (handler, flag);
}


extern "C" void upt_jd_diag_ (f77_int const*, f77_int const&, f77_int const&, 
    f77_int const&, f77_int const&, f77_double const&, f77_double const&, 
    f77_double const&);

// Corresponding F77 arguments for f77_upt_jd_diag:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: st_vb
// integer, intent(in) :: st_cb
// integer, intent(in) :: n_vb
// integer, intent(in) :: n_cb
// real(dp), intent(in) :: guess_vb
// real(dp), intent(in) :: guess_cb
// real(dp), intent(in) :: long_tol
inline void f77_upt_jd_diag (f77_int const* handler, f77_int const& st_vb, 
    f77_int const& st_cb, f77_int const& n_vb, f77_int const& n_cb, f77_double 
    const& guess_vb, f77_double const& guess_cb, f77_double const& long_tol)
{
  upt_jd_diag_ (handler, st_vb, st_cb, n_vb, n_cb, guess_vb, guess_cb, 
      long_tol);
}


extern "C" void upt_feastsolver_ (f77_int const*, f77_double const&, f77_double 
    const&, f77_int const&);

// Corresponding F77 arguments for f77_upt_feastsolver:
// integer, intent(in) :: handler(DAC_handlerSize)
// real(dp), intent(in) :: emin
// real(dp), intent(in) :: emax
// integer, intent(in) :: m0
inline void f77_upt_feastsolver (f77_int const* handler, f77_double const& 
    emin, f77_double const& emax, f77_int const& m0)
{
  upt_feastsolver_ (handler, emin, emax, m0);
}


extern "C" void upt_lapacksolver_ (f77_int const*, f77_int const&, f77_int 
    const&, f77_double const&, f77_double const&);

// Corresponding F77 arguments for f77_upt_lapacksolver:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: n_vb
// integer, intent(in) :: n_cb
// real(dp), intent(in) :: guess_vb
// real(dp), intent(in) :: guess_cb
inline void f77_upt_lapacksolver (f77_int const* handler, f77_int const& n_vb, 
    f77_int const& n_cb, f77_double const& guess_vb, f77_double const& guess_cb)
{
  upt_lapacksolver_ (handler, n_vb, n_cb, guess_vb, guess_cb);
}


extern "C" void upt_alloc_states_ (f77_int const*);

// Corresponding F77 arguments for f77_upt_alloc_states:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_upt_alloc_states (f77_int const* handler)
{
  upt_alloc_states_ (handler);
}


extern "C" void upt_write_states_ (f77_int const*);

// Corresponding F77 arguments for f77_upt_write_states:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_upt_write_states (f77_int const* handler)
{
  upt_write_states_ (handler);
}


extern "C" void upt_set_num_states_ (f77_int const*, f77_int const&, f77_int 
    const&);

// Corresponding F77 arguments for f77_upt_set_num_states:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: n_vb
// integer, intent(in) :: n_cb
inline void f77_upt_set_num_states (f77_int const* handler, f77_int const& 
    n_vb, f77_int const& n_cb)
{
  upt_set_num_states_ (handler, n_vb, n_cb);
}


extern "C" void upt_read_states_ (f77_int const*, f77_char const*, f77_int&, 
    f77_int&);

// Corresponding F77 arguments for f77_upt_read_states:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: filename(1)
// integer, intent(inout) :: nev
// integer, intent(inout) :: nec
inline void f77_upt_read_states (f77_int const* handler, f77_char const* 
    filename, f77_int& nev, f77_int& nec)
{
  upt_read_states_ (handler, filename, nev, nec);
}


extern "C" void upt_get_hamildim_ (f77_int const*, f77_int&);

// Corresponding F77 arguments for f77_upt_get_hamildim:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(out) :: hdim
inline void f77_upt_get_hamildim (f77_int const* handler, f77_int& hdim)
{
  upt_get_hamildim_ (handler, hdim);
}


extern "C" void upt_get_hamilnnz_ (f77_int const*, f77_int&);

// Corresponding F77 arguments for f77_upt_get_hamilnnz:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(out) :: nnz
inline void f77_upt_get_hamilnnz (f77_int const* handler, f77_int& nnz)
{
  upt_get_hamilnnz_ (handler, nnz);
}


extern "C" void upt_get_hamil_rowsize_ (f77_int const*, f77_int const&, 
    f77_int&);

// Corresponding F77 arguments for f77_upt_get_hamil_rowsize:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: row
// integer, intent(out) :: sz
inline void f77_upt_get_hamil_rowsize (f77_int const* handler, f77_int const& 
    row, f77_int& sz)
{
  upt_get_hamil_rowsize_ (handler, row, sz);
}


extern "C" void upt_get_hamil_row_ (f77_int const*, f77_int const&, f77_int*, 
    f77_complex*);

// Corresponding F77 arguments for f77_upt_get_hamil_row:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: row
// integer, intent(inout) :: colind(*)
// complex(dp), intent(inout) :: vals(*)
inline void f77_upt_get_hamil_row (f77_int const* handler, f77_int const& row, 
    f77_int* colind, f77_complex* vals)
{
  upt_get_hamil_row_ (handler, row, colind, vals);
}


extern "C" void upt_get_csr_hamiltonian_ (f77_int const*, f77_int&, f77_char&, 
    f77_complex*, f77_int*, f77_int*);

// Corresponding F77 arguments for f77_upt_get_csr_hamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(out) :: nrow
// character(1), intent(out) :: fmt
// complex(dp), intent(out) :: A(1)
// integer, intent(out) :: JA(1)
// integer, intent(out) :: IA(1)
inline void f77_upt_get_csr_hamiltonian (f77_int const* handler, f77_int& nrow, 
    f77_char& fmt, f77_complex* A, f77_int* JA, f77_int* IA)
{
  upt_get_csr_hamiltonian_ (handler, nrow, fmt, A, JA, IA);
}


extern "C" void upt_set_csr_hamiltonian_ (f77_int const*, f77_int&, f77_char&, 
    f77_complex*, f77_int*, f77_int*);

// Corresponding F77 arguments for f77_upt_set_csr_hamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(out) :: nrow
// character(1), intent(out) :: fmt
// complex(dp), intent(out) :: A(*)
// integer, intent(out) :: JA(*)
// integer, intent(out) :: IA(*)
inline void f77_upt_set_csr_hamiltonian (f77_int const* handler, f77_int& nrow, 
    f77_char& fmt, f77_complex* A, f77_int* JA, f77_int* IA)
{
  upt_set_csr_hamiltonian_ (handler, nrow, fmt, A, JA, IA);
}


extern "C" void upt_get_states_ (f77_int const*, f77_int const&, f77_int 
    const&, f77_double*, f77_complex*, f77_int*);

// Corresponding F77 arguments for f77_upt_get_states:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: num_ev
// integer, intent(in) :: hdim
// real(dp), intent(out) :: eigenvals(num_ev)
// complex(dp), intent(out) :: eigenstates(hdim, num_ev)
// integer, intent(out) :: types(num_ev)
inline void f77_upt_get_states (f77_int const* handler, f77_int const& num_ev, 
    f77_int const& hdim, f77_double* eigenvals, f77_complex* eigenstates, 
    f77_int* types)
{
  upt_get_states_ (handler, num_ev, hdim, eigenvals, eigenstates, types);
}


extern "C" void upt_set_state_ (f77_int const*, f77_int const&, f77_int const&, 
    f77_int const&, f77_double const&, f77_complex const*, f77_int const&);

// Corresponding F77 arguments for f77_upt_set_state:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: num_ev
// integer, intent(in) :: id
// integer, intent(in) :: hdim
// real(dp), intent(in) :: eigenval
// complex(dp), intent(in) :: eigenstate(hdim)
// integer, intent(in) :: particle
inline void f77_upt_set_state (f77_int const* handler, f77_int const& num_ev, 
    f77_int const& id, f77_int const& hdim, f77_double const& eigenval, 
    f77_complex const* eigenstate, f77_int const& particle)
{
  upt_set_state_ (handler, num_ev, id, hdim, eigenval, eigenstate, particle);
}


extern "C" void upt_get_matel_ (f77_int const*, f77_int const&, f77_int const&, 
    f77_complex&);

// Corresponding F77 arguments for f77_upt_get_matel:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: i
// integer, intent(in) :: j
// complex(dp), intent(out) :: matel
inline void f77_upt_get_matel (f77_int const* handler, f77_int const& i, 
    f77_int const& j, f77_complex& matel)
{
  upt_get_matel_ (handler, i, j, matel);
}


extern "C" void upt_project_pot_ (f77_int const*, f77_int const&, f77_double 
    const*, f77_double&);

// Corresponding F77 arguments for f77_upt_project_pot:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: i
// real(dp), intent(in) :: potential(1)
// real(dp), intent(out) :: average
inline void f77_upt_project_pot (f77_int const* handler, f77_int const& i, 
    f77_double const* potential, f77_double& average)
{
  upt_project_pot_ (handler, i, potential, average);
}


extern "C" void upt_get_ion_numorbitals_ (f77_int const*, f77_int*);

// Corresponding F77 arguments for f77_upt_get_ion_numorbitals:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(inout) :: ion_block_vector(*)
inline void f77_upt_get_ion_numorbitals (f77_int const* handler, f77_int* 
    ion_block_vector)
{
  upt_get_ion_numorbitals_ (handler, ion_block_vector);
}


extern "C" void upt_get_ion_orbitals_ (f77_int const*, f77_int&, f77_int*);

// Corresponding F77 arguments for f77_upt_get_ion_orbitals:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(inout) :: ion
// integer, intent(inout) :: orbitals(*)
inline void f77_upt_get_ion_orbitals (f77_int const* handler, f77_int& ion, 
    f77_int* orbitals)
{
  upt_get_ion_orbitals_ (handler, ion, orbitals);
}


extern "C" void upt_set_verbosity_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_upt_set_verbosity:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: verbose_lev
inline void f77_upt_set_verbosity (f77_int const* handler, f77_int const& 
    verbose_lev)
{
  upt_set_verbosity_ (handler, verbose_lev);
}


extern "C" void real_test_ (f77_double&);

// Corresponding F77 arguments for f77_real_test:
// real(dp), intent(out) :: re
inline void f77_real_test (f77_double& re)
{
  real_test_ (re);
}


extern "C" void complex_test_ (f77_double&, f77_double&, f77_complex&);

// Corresponding F77 arguments for f77_complex_test:
// real(dp), intent(out) :: re
// real(dp), intent(out) :: im
// complex(dp), intent(out) :: zz
inline void f77_complex_test (f77_double& re, f77_double& im, f77_complex& zz)
{
  complex_test_ (re, im, zz);
}


extern "C" void upt_setstrain_ (f77_int const*, f77_int const&, f77_double 
    const*, f77_double const*, f77_double const*);

// Corresponding F77 arguments for f77_upt_setstrain:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nAtoms
// real(dp), intent(in) :: strain_xx(nAtoms)
// real(dp), intent(in) :: strain_yy(nAtoms)
// real(dp), intent(in) :: strain_zz(nAtoms)
inline void f77_upt_setstrain (f77_int const* handler, f77_int const& nAtoms, 
    f77_double const* strain_xx, f77_double const* strain_yy, f77_double const* 
    strain_zz)
{
  upt_setstrain_ (handler, nAtoms, strain_xx, strain_yy, strain_zz);
}


#endif

