#ifndef _UPTP_H
#define _UPTP_H

//*************************************************************************** 
//*
//*  C++ bindings for UPTIGHT 
//*
//*  Generated by bind_fortran (DO NOT EDIT MANUALLY)
//*
//***************************************************************************
//* Notes:
//*   o) these bindings need the "fortran.h" header file
//*   o) you should call only the f77_* functions from C++ in order to make
//*      sure, that your code does not depend on the naming convention of
//*      the different compilers (e.g. trailing underscores)
//***************************************************************************

#include "fortran.h"

// Some defintions for constants used by Uptight
const int UPT_SC = 100;
const int UPT_MC = 200;
const int UPT_LC = 500;
const int UPT_HSIZE = 4;
const char UPT_PADCHAR = ' ';



// Corresponding F77 arguments for upt_gethandlersize:
// integer, intent(out) :: handlerSize
extern "C"

{
  void upt_gethandlersize_ (int& handlerSize);
}


// Corresponding F77 arguments for upt_initsession:
// integer, intent(out) :: handler(DAC_handlerSize)
extern "C"

{
  void upt_initsession_ (int* handler);
}


// Corresponding F77 arguments for upt_destructsession:
// integer, intent(inout) :: handler(DAC_handlerSize)
extern "C"

{
  void upt_destructsession_ (int* handler);
}


// Corresponding F77 arguments for upt_getversion:
// integer, intent(in) :: handler(DAC_handlerSize)
extern "C"

{
  void upt_getversion_ (int const* handler);
}


// Corresponding F77 arguments for upt_setmpicomm:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: comm
extern "C"

{
  void upt_setmpicomm_ (int const* handler, int const& comm);
}


// Corresponding F77 arguments for upt_set_paths:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: databasePath(1)
// character(LST), intent(in) :: workPath(1)
// character(LST), intent(in) :: outPath(1)
extern "C"

{
  void upt_set_paths_ (int const* handler, f77_char const* databasePath, 
      f77_char const* workPath, f77_char const* outPath);
}


// Corresponding F77 arguments for upt_fillbasicparameters:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: verbose_lev
// character(MST), intent(in) :: gen_filename(1)
// character(MST), intent(in) :: gen_outname(1)
// character(MST), intent(in) :: sparse_fmt(1)
// integer, intent(in) :: max_n_n
// integer, intent(in) :: harrison_flag
// integer, intent(in) :: relat_flag
// integer, intent(in) :: potential_flag
// integer, intent(in) :: optmat_flag
// integer, intent(in) :: poldir
// real(dp), intent(in) :: c_axis_x
// real(dp), intent(in) :: c_axis_y
// real(dp), intent(in) :: c_axis_z
// integer, intent(in) :: check_bondmap
// real(dp), intent(in) :: dg_coupl_scale
// real(dp), intent(in) :: dg_onsite
// integer, intent(in) :: hybrid_passivation
extern "C"

{
  void upt_fillbasicparameters_ (int const* handler, int const& verbose_lev, 
      f77_char const* gen_filename, f77_char const* gen_outname, f77_char 
      const* sparse_fmt, int const& max_n_n, int const& harrison_flag, int 
      const& relat_flag, int const& potential_flag, int const& optmat_flag, int 
      const& poldir, f77_double const& c_axis_x, f77_double const& c_axis_y, 
      f77_double const& c_axis_z, int const& check_bondmap, f77_double const& 
      dg_coupl_scale, f77_double const& dg_onsite, int const& 
      hybrid_passivation);
}


// Corresponding F77 arguments for upt_setworkpath:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: workPath(1)
extern "C"

{
  void upt_setworkpath_ (int const* handler, f77_char const* workPath);
}


// Corresponding F77 arguments for upt_setoutpath:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: outPath(1)
extern "C"

{
  void upt_setoutpath_ (int const* handler, f77_char const* outPath);
}


// Corresponding F77 arguments for upt_setloadpath:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: loadPath(1)
extern "C"

{
  void upt_setloadpath_ (int const* handler, f77_char const* loadPath);
}


// Corresponding F77 arguments for upt_setstatefile:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: filename(1)
extern "C"

{
  void upt_setstatefile_ (int const* handler, f77_char const* filename);
}


// Corresponding F77 arguments for upt_setoutput:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: out_form
// real(dp), intent(in) :: step
extern "C"

{
  void upt_setoutput_ (int const* handler, int const& out_form, f77_double 
      const& step);
}


// Corresponding F77 arguments for upt_setpmatrix:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: optmat_flag
// integer, intent(in) :: poldir
extern "C"

{
  void upt_setpmatrix_ (int const* handler, int const& optmat_flag, int const& 
      poldir);
}


// Corresponding F77 arguments for upt_inituptight:
// integer, intent(in) :: handler(DAC_handlerSize)
extern "C"

{
  void upt_inituptight_ (int const* handler);
}


// Corresponding F77 arguments for upt_destructuptight:
// integer, intent(in) :: handler(DAC_handlerSize)
extern "C"

{
  void upt_destructuptight_ (int const* handler);
}


// Corresponding F77 arguments for upt_addpotential:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nAtoms
// real(dp), intent(in) :: potential(nAtoms)
extern "C"

{
  void upt_addpotential_ (int const* handler, int const& nAtoms, f77_double 
      const* potential);
}


// Corresponding F77 arguments for upt_erasepotential:
// integer, intent(in) :: handler(DAC_handlerSize)
extern "C"

{
  void upt_erasepotential_ (int const* handler);
}


// Corresponding F77 arguments for upt_createhamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(MST), intent(in) :: sparse_fmt(1)
extern "C"

{
  void upt_createhamiltonian_ (int const* handler, f77_char const* sparse_fmt);
}


// Corresponding F77 arguments for upt_set_coarse_graining:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: enabled
// integer, intent(in) :: n_blocks
// real(dp), intent(in) :: emin
// real(dp), intent(in) :: emax
// real(dp), intent(in) :: imbalance
extern "C"

{
  void upt_set_coarse_graining_ (int const* handler, int const& enabled, int 
      const& n_blocks, f77_double const& emin, f77_double const& emax, 
      f77_double const& imbalance);
}


// Corresponding F77 arguments for upt_set_coarse_graining_mode:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: mode
// integer, intent(in) :: subsolver
// integer, intent(in) :: subsolver_type
// integer, intent(in) :: n_blocks
// real(dp), intent(in) :: imbalance
// real(dp), intent(in) :: energy_min
// real(dp), intent(in) :: energy_max
// real(dp), intent(in) :: core_energy_min
// real(dp), intent(in) :: core_energy_max
// real(dp), intent(in) :: energy_buffer
// real(dp), intent(in) :: epsilon
// integer, intent(in) :: neumann_order
// real(dp), intent(in) :: expansion_energy
// integer, intent(in) :: check_convergence
// integer, intent(in) :: power_iteration_max_iterations
// real(dp), intent(in) :: power_iteration_tolerance
extern "C"

{
  void upt_set_coarse_graining_mode_ (int const* handler, int const& mode, int 
      const& subsolver, int const& subsolver_type, int const& n_blocks, 
      f77_double const& imbalance, f77_double const& energy_min, f77_double 
      const& energy_max, f77_double const& core_energy_min, f77_double const& 
      core_energy_max, f77_double const& energy_buffer, f77_double const& 
      epsilon, int const& neumann_order, f77_double const& expansion_energy, 
      int const& check_convergence, int const& power_iteration_max_iterations, 
      f77_double const& power_iteration_tolerance);
}


// Corresponding F77 arguments for upt_get_coarse_graining_info:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(out) :: ready
// integer, intent(out) :: original_dim
// integer, intent(out) :: reduced_dim
// integer, intent(out) :: n_blocks
// real(dp), intent(out) :: cut_fraction
extern "C"

{
  void upt_get_coarse_graining_info_ (int const* handler, int& ready, int& 
      original_dim, int& reduced_dim, int& n_blocks, f77_double& cut_fraction);
}


// Corresponding F77 arguments for upt_printhamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
extern "C"

{
  void upt_printhamiltonian_ (int const* handler);
}


// Corresponding F77 arguments for upt_setkpoint:
// integer, intent(in) :: handler(DAC_handlerSize)
// real(dp), intent(in) :: k_vec(3)
extern "C"

{
  void upt_setkpoint_ (int const* handler, f77_double const* k_vec);
}


// Corresponding F77 arguments for upt_lanczosdiag:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: st_vb
// integer, intent(in) :: st_cb
// integer, intent(in) :: n_vb
// integer, intent(in) :: n_cb
// real(dp), intent(in) :: guess_vb
// real(dp), intent(in) :: guess_cb
// integer, intent(in) :: min_iter
// integer, intent(in) :: long_iter
// integer, intent(in) :: max_iter
// real(dp), intent(in) :: fast_tol
// real(dp), intent(in) :: long_tol
// real(dp), intent(in) :: ort_tol
// integer, intent(in) :: dynamic
// real(dp), intent(in) :: bitoff
extern "C"

{
  void upt_lanczosdiag_ (int const* handler, int const& st_vb, int const& 
      st_cb, int const& n_vb, int const& n_cb, f77_double const& guess_vb, 
      f77_double const& guess_cb, int const& min_iter, int const& long_iter, 
      int const& max_iter, f77_double const& fast_tol, f77_double const& 
      long_tol, f77_double const& ort_tol, int const& dynamic, f77_double 
      const& bitoff);
}


// Corresponding F77 arguments for upt_solver_flag:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: flag
extern "C"

{
  void upt_solver_flag_ (int const* handler, int const& flag);
}


// Corresponding F77 arguments for upt_jd_diag:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: st_vb
// integer, intent(in) :: st_cb
// integer, intent(in) :: n_vb
// integer, intent(in) :: n_cb
// real(dp), intent(in) :: guess_vb
// real(dp), intent(in) :: guess_cb
// real(dp), intent(in) :: long_tol
extern "C"

{
  void upt_jd_diag_ (int const* handler, int const& st_vb, int const& st_cb, 
      int const& n_vb, int const& n_cb, f77_double const& guess_vb, f77_double 
      const& guess_cb, f77_double const& long_tol);
}


// Corresponding F77 arguments for upt_feastsolver:
// integer, intent(in) :: handler(DAC_handlerSize)
// real(dp), intent(in) :: emin
// real(dp), intent(in) :: emax
// integer, intent(in) :: m0
extern "C"

{
  void upt_feastsolver_ (int const* handler, f77_double const& emin, f77_double 
      const& emax, int const& m0);
}


// Corresponding F77 arguments for upt_lapacksolver:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: n_vb
// integer, intent(in) :: n_cb
// real(dp), intent(in) :: guess_vb
// real(dp), intent(in) :: guess_cb
extern "C"

{
  void upt_lapacksolver_ (int const* handler, int const& n_vb, int const& n_cb, 
      f77_double const& guess_vb, f77_double const& guess_cb);
}


// Corresponding F77 arguments for upt_alloc_states:
// integer, intent(in) :: handler(DAC_handlerSize)
extern "C"

{
  void upt_alloc_states_ (int const* handler);
}


// Corresponding F77 arguments for upt_write_states:
// integer, intent(in) :: handler(DAC_handlerSize)
extern "C"

{
  void upt_write_states_ (int const* handler);
}


// Corresponding F77 arguments for upt_set_num_states:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: n_vb
// integer, intent(in) :: n_cb
extern "C"

{
  void upt_set_num_states_ (int const* handler, int const& n_vb, int const& 
      n_cb);
}


// Corresponding F77 arguments for upt_read_states:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: filename(1)
// integer, intent(inout) :: nev
// integer, intent(inout) :: nec
extern "C"

{
  void upt_read_states_ (int const* handler, f77_char const* filename, int& 
      nev, int& nec);
}


// Corresponding F77 arguments for upt_get_hamildim:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(out) :: hdim
extern "C"

{
  void upt_get_hamildim_ (int const* handler, int& hdim);
}


// Corresponding F77 arguments for upt_get_hamilnnz:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(out) :: nnz
extern "C"

{
  void upt_get_hamilnnz_ (int const* handler, int& nnz);
}


// Corresponding F77 arguments for upt_get_hamil_rowsize:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: row
// integer, intent(out) :: sz
extern "C"

{
  void upt_get_hamil_rowsize_ (int const* handler, int const& row, int& sz);
}


// Corresponding F77 arguments for upt_get_hamil_row:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: row
// integer, intent(inout) :: colind(*)
// complex(dp), intent(inout) :: vals(*)
extern "C"

{
  void upt_get_hamil_row_ (int const* handler, int const& row, int* colind, 
      f77_complex* vals);
}


// Corresponding F77 arguments for upt_get_csr_hamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(out) :: nrow
// character(1), intent(out) :: fmt
// complex(dp), intent(out) :: A(1)
// integer, intent(out) :: JA(1)
// integer, intent(out) :: IA(1)
extern "C"

{
  void upt_get_csr_hamiltonian_ (int const* handler, int& nrow, f77_char& fmt, 
      f77_complex* A, int* JA, int* IA);
}


// Corresponding F77 arguments for upt_set_csr_hamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(out) :: nrow
// character(1), intent(out) :: fmt
// complex(dp), intent(out) :: A(*)
// integer, intent(out) :: JA(*)
// integer, intent(out) :: IA(*)
extern "C"

{
  void upt_set_csr_hamiltonian_ (int const* handler, int& nrow, f77_char& fmt, 
      f77_complex* A, int* JA, int* IA);
}


// Corresponding F77 arguments for upt_get_states:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: num_ev
// integer, intent(in) :: hdim
// real(dp), intent(out) :: eigenvals(num_ev)
// complex(dp), intent(out) :: eigenstates(hdim, num_ev)
// integer, intent(out) :: types(num_ev)
extern "C"

{
  void upt_get_states_ (int const* handler, int const& num_ev, int const& hdim, 
      f77_double* eigenvals, f77_complex* eigenstates, int* types);
}


// Corresponding F77 arguments for upt_set_state:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: num_ev
// integer, intent(in) :: id
// integer, intent(in) :: hdim
// real(dp), intent(in) :: eigenval
// complex(dp), intent(in) :: eigenstate(hdim)
// integer, intent(in) :: particle
extern "C"

{
  void upt_set_state_ (int const* handler, int const& num_ev, int const& id, 
      int const& hdim, f77_double const& eigenval, f77_complex const* 
      eigenstate, int const& particle);
}


// Corresponding F77 arguments for upt_get_matel:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: i
// integer, intent(in) :: j
// complex(dp), intent(out) :: matel
extern "C"

{
  void upt_get_matel_ (int const* handler, int const& i, int const& j, 
      f77_complex& matel);
}


// Corresponding F77 arguments for upt_project_pot:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: i
// real(dp), intent(in) :: potential(1)
// real(dp), intent(out) :: average
extern "C"

{
  void upt_project_pot_ (int const* handler, int const& i, f77_double const* 
      potential, f77_double& average);
}


// Corresponding F77 arguments for upt_get_ion_numorbitals:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(inout) :: ion_block_vector(*)
extern "C"

{
  void upt_get_ion_numorbitals_ (int const* handler, int* ion_block_vector);
}


// Corresponding F77 arguments for upt_get_ion_orbitals:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(inout) :: ion
// integer, intent(inout) :: orbitals(*)
extern "C"

{
  void upt_get_ion_orbitals_ (int const* handler, int& ion, int* orbitals);
}


// Corresponding F77 arguments for upt_set_verbosity:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: verbose_lev
extern "C"

{
  void upt_set_verbosity_ (int const* handler, int const& verbose_lev);
}


// Corresponding F77 arguments for real_test:
// real(dp), intent(out) :: re
extern "C"

{
  void real_test_ (f77_double& re);
}


// Corresponding F77 arguments for complex_test:
// real(dp), intent(out) :: re
// real(dp), intent(out) :: im
// complex(dp), intent(out) :: zz
extern "C"

{
  void complex_test_ (f77_double& re, f77_double& im, f77_complex& zz);
}


// Corresponding F77 arguments for upt_setstrain:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nAtoms
// real(dp), intent(in) :: strain_xx(nAtoms)
// real(dp), intent(in) :: strain_yy(nAtoms)
// real(dp), intent(in) :: strain_zz(nAtoms)
extern "C"

{
  void upt_setstrain_ (int const* handler, int const& nAtoms, f77_double const* 
      strain_xx, f77_double const* strain_yy, f77_double const* strain_zz);
}


#endif

