#ifndef _UPTP_H
#define _UPTP_H

/**************************************************************************** 
 *
 *  C bindings for UPTIGHT 
 *
 *  Generated by bind_fortran (DO NOT EDIT MANUALLY)
 *
 ****************************************************************************/


#define UPT_SC  100
#define UPT_MC  200
#define UPT_LC  500
#define UPT_HSIZE 4
#define UPT_PADCHAR ' '


void upt_gethandlersize_(int *handlerSize);
/* integer, intent(out) :: handlerSize  */

void upt_initsession_(int *handler);
/* integer, intent(out) :: handler(DAC_handlerSize)  */

void upt_destructsession_(int *handler);
/* integer, intent(inout) :: handler(DAC_handlerSize)  */

void upt_getversion_(const int *handler);
/* integer, intent(in) :: handler(DAC_handlerSize)  */

void upt_setmpicomm_(const int *handler, const int *comm);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: comm  */

void upt_set_paths_(const int *handler, const char *databasePath, const char 
    *workPath, const char *outPath);
/* integer, intent(in) :: handler(DAC_handlerSize)
   character(LST), intent(in) :: databasePath(1)
   character(LST), intent(in) :: workPath(1)
   character(LST), intent(in) :: outPath(1)  */

void upt_fillbasicparameters_(const int *handler, const int *verbose_lev, const 
    char *gen_filename, const char *gen_outname, const char *sparse_fmt, const 
    int *max_n_n, const int *harrison_flag, const int *relat_flag, const int 
    *potential_flag, const int *optmat_flag, const int *poldir, const double 
    *c_axis_x, const double *c_axis_y, const double *c_axis_z, const int 
    *check_bondmap, const double *dg_coupl_scale, const double *dg_onsite, 
    const int *hybrid_passivation);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: verbose_lev
   character(MST), intent(in) :: gen_filename(1)
   character(MST), intent(in) :: gen_outname(1)
   character(MST), intent(in) :: sparse_fmt(1)
   integer, intent(in) :: max_n_n
   integer, intent(in) :: harrison_flag
   integer, intent(in) :: relat_flag
   integer, intent(in) :: potential_flag
   integer, intent(in) :: optmat_flag
   integer, intent(in) :: poldir
   real(dp), intent(in) :: c_axis_x
   real(dp), intent(in) :: c_axis_y
   real(dp), intent(in) :: c_axis_z
   integer, intent(in) :: check_bondmap
   real(dp), intent(in) :: dg_coupl_scale
   real(dp), intent(in) :: dg_onsite
   integer, intent(in) :: hybrid_passivation  */

void upt_setworkpath_(const int *handler, const char *workPath);
/* integer, intent(in) :: handler(DAC_handlerSize)
   character(LST), intent(in) :: workPath(1)  */

void upt_setoutpath_(const int *handler, const char *outPath);
/* integer, intent(in) :: handler(DAC_handlerSize)
   character(LST), intent(in) :: outPath(1)  */

void upt_setloadpath_(const int *handler, const char *loadPath);
/* integer, intent(in) :: handler(DAC_handlerSize)
   character(LST), intent(in) :: loadPath(1)  */

void upt_setstatefile_(const int *handler, const char *filename);
/* integer, intent(in) :: handler(DAC_handlerSize)
   character(LST), intent(in) :: filename(1)  */

void upt_setoutput_(const int *handler, const int *out_form, const double 
    *step);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: out_form
   real(dp), intent(in) :: step  */

void upt_setpmatrix_(const int *handler, const int *optmat_flag, const int 
    *poldir);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: optmat_flag
   integer, intent(in) :: poldir  */

void upt_inituptight_(const int *handler);
/* integer, intent(in) :: handler(DAC_handlerSize)  */

void upt_destructuptight_(const int *handler);
/* integer, intent(in) :: handler(DAC_handlerSize)  */

void upt_addpotential_(const int *handler, const int *nAtoms, const double 
    *potential);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: nAtoms
   real(dp), intent(in) :: potential(nAtoms)  */

void upt_erasepotential_(const int *handler);
/* integer, intent(in) :: handler(DAC_handlerSize)  */

void upt_createhamiltonian_(const int *handler, const char *sparse_fmt);
/* integer, intent(in) :: handler(DAC_handlerSize)
   character(MST), intent(in) :: sparse_fmt(1)  */

void upt_set_coarse_graining_(const int *handler, const int *enabled, const int 
    *n_blocks, const double *emin, const double *emax, const double *imbalance);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: enabled
   integer, intent(in) :: n_blocks
   real(dp), intent(in) :: emin
   real(dp), intent(in) :: emax
   real(dp), intent(in) :: imbalance  */

void upt_get_coarse_graining_info_(const int *handler, int *ready, int 
    *original_dim, int *reduced_dim, int *n_blocks, double *cut_fraction);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(out) :: ready
   integer, intent(out) :: original_dim
   integer, intent(out) :: reduced_dim
   integer, intent(out) :: n_blocks
   real(dp), intent(out) :: cut_fraction  */

void upt_printhamiltonian_(const int *handler);
/* integer, intent(in) :: handler(DAC_handlerSize)  */

void upt_setkpoint_(const int *handler, const double *k_vec);
/* integer, intent(in) :: handler(DAC_handlerSize)
   real(dp), intent(in) :: k_vec(3)  */

void upt_lanczosdiag_(const int *handler, const int *st_vb, const int *st_cb, 
    const int *n_vb, const int *n_cb, const double *guess_vb, const double 
    *guess_cb, const int *min_iter, const int *long_iter, const int *max_iter, 
    const double *fast_tol, const double *long_tol, const double *ort_tol, 
    const int *dynamic, const double *bitoff);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: st_vb
   integer, intent(in) :: st_cb
   integer, intent(in) :: n_vb
   integer, intent(in) :: n_cb
   real(dp), intent(in) :: guess_vb
   real(dp), intent(in) :: guess_cb
   integer, intent(in) :: min_iter
   integer, intent(in) :: long_iter
   integer, intent(in) :: max_iter
   real(dp), intent(in) :: fast_tol
   real(dp), intent(in) :: long_tol
   real(dp), intent(in) :: ort_tol
   integer, intent(in) :: dynamic
   real(dp), intent(in) :: bitoff  */

void upt_solver_flag_(const int *handler, const int *flag);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: flag  */

void upt_jd_diag_(const int *handler, const int *st_vb, const int *st_cb, const 
    int *n_vb, const int *n_cb, const double *guess_vb, const double *guess_cb, 
    const double *long_tol);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: st_vb
   integer, intent(in) :: st_cb
   integer, intent(in) :: n_vb
   integer, intent(in) :: n_cb
   real(dp), intent(in) :: guess_vb
   real(dp), intent(in) :: guess_cb
   real(dp), intent(in) :: long_tol  */

void upt_feastsolver_(const int *handler, const double *emin, const double 
    *emax, const int *m0);
/* integer, intent(in) :: handler(DAC_handlerSize)
   real(dp), intent(in) :: emin
   real(dp), intent(in) :: emax
   integer, intent(in) :: m0  */

void upt_lapacksolver_(const int *handler, const int *n_vb, const int *n_cb, 
    const double *guess_vb, const double *guess_cb);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: n_vb
   integer, intent(in) :: n_cb
   real(dp), intent(in) :: guess_vb
   real(dp), intent(in) :: guess_cb  */

void upt_alloc_states_(const int *handler);
/* integer, intent(in) :: handler(DAC_handlerSize)  */

void upt_write_states_(const int *handler);
/* integer, intent(in) :: handler(DAC_handlerSize)  */

void upt_set_num_states_(const int *handler, const int *n_vb, const int *n_cb);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: n_vb
   integer, intent(in) :: n_cb  */

void upt_read_states_(const int *handler, const char *filename, int *nev, int 
    *nec);
/* integer, intent(in) :: handler(DAC_handlerSize)
   character(LST), intent(in) :: filename(1)
   integer, intent(inout) :: nev
   integer, intent(inout) :: nec  */

void upt_get_hamildim_(const int *handler, int *hdim);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(out) :: hdim  */

void upt_get_hamilnnz_(const int *handler, int *nnz);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(out) :: nnz  */

void upt_get_hamil_rowsize_(const int *handler, const int *row, int *sz);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: row
   integer, intent(out) :: sz  */

void upt_get_hamil_row_(const int *handler, const int *row, int *colind, double 
    *vals);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: row
   integer, intent(inout) :: colind(*)
   complex(dp), intent(inout) :: vals(*)  */

void upt_get_csr_hamiltonian_(const int *handler, int *nrow, char *fmt, double 
    *A, int *JA, int *IA);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(out) :: nrow
   character(1), intent(out) :: fmt
   complex(dp), intent(out) :: A(1)
   integer, intent(out) :: JA(1)
   integer, intent(out) :: IA(1)  */

void upt_set_csr_hamiltonian_(const int *handler, int *nrow, char *fmt, double 
    *A, int *JA, int *IA);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(out) :: nrow
   character(1), intent(out) :: fmt
   complex(dp), intent(out) :: A(*)
   integer, intent(out) :: JA(*)
   integer, intent(out) :: IA(*)  */

void upt_get_states_(const int *handler, const int *num_ev, const int *hdim, 
    double *eigenvals, double *eigenstates, int *types);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: num_ev
   integer, intent(in) :: hdim
   real(dp), intent(out) :: eigenvals(num_ev)
   complex(dp), intent(out) :: eigenstates(hdim, num_ev)
   integer, intent(out) :: types(num_ev)  */

void upt_set_state_(const int *handler, const int *num_ev, const int *id, const 
    int *hdim, const double *eigenval, const double *eigenstate, const int 
    *particle);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: num_ev
   integer, intent(in) :: id
   integer, intent(in) :: hdim
   real(dp), intent(in) :: eigenval
   complex(dp), intent(in) :: eigenstate(hdim)
   integer, intent(in) :: particle  */

void upt_get_matel_(const int *handler, const int *i, const int *j, double 
    *matel);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: i
   integer, intent(in) :: j
   complex(dp), intent(out) :: matel  */

void upt_project_pot_(const int *handler, const int *i, const double 
    *potential, double *average);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: i
   real(dp), intent(in) :: potential(1)
   real(dp), intent(out) :: average  */

void upt_get_ion_numorbitals_(const int *handler, int *ion_block_vector);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(inout) :: ion_block_vector(*)  */

void upt_get_ion_orbitals_(const int *handler, int *ion, int *orbitals);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(inout) :: ion
   integer, intent(inout) :: orbitals(*)  */

void upt_set_verbosity_(const int *handler, const int *verbose_lev);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: verbose_lev  */

void real_test_(double *re);
/* real(dp), intent(out) :: re  */

void complex_test_(double *re, double *im, double *zz);
/* real(dp), intent(out) :: re
   real(dp), intent(out) :: im
   complex(dp), intent(out) :: zz  */

void upt_setstrain_(const int *handler, const int *nAtoms, const double 
    *strain_xx, const double *strain_yy, const double *strain_zz);
/* integer, intent(in) :: handler(DAC_handlerSize)
   integer, intent(in) :: nAtoms
   real(dp), intent(in) :: strain_xx(nAtoms)
   real(dp), intent(in) :: strain_yy(nAtoms)
   real(dp), intent(in) :: strain_zz(nAtoms)  */

#endif

