#ifndef _UPTP_H
#define _UPTP_H

//*************************************************************************** 
//*
//*  C++ bindings for UPTIGHT 
//*
//*  Generated by bind_fortran (DO NOT EDIT MANUALLY)
//*
//***************************************************************************
//* Notes:
//*   o) these bindings need the "fortran.h" header file
//*   o) you should call only the f77_* functions from C++ in order to make
//*      sure, that your code does not depend on the naming convention of
//*      the different compilers (e.g. trailing underscores)
//***************************************************************************

#include "fortran.h"

// Some defintions for constants used by Uptight
const int UPT_MC = 200;
const int UPT_LC = 500;
const int UPT_HSIZE = 4;
const char UPT_PADCHAR = ' ';



extern "C" void upt_gethandlersize_ (f77_int&);

// Corresponding F77 arguments for f77_upt_gethandlersize:
// integer, intent(out) :: handlerSize
inline void f77_upt_gethandlersize (f77_int& handlerSize)
{
  upt_gethandlersize_ (handlerSize);
}


extern "C" void upt_initsession_ (f77_int*);

// Corresponding F77 arguments for f77_upt_initsession:
// integer, intent(out) :: handler(DAC_handlerSize)
inline void f77_upt_initsession (f77_int* handler)
{
  upt_initsession_ (handler);
}


extern "C" void upt_destructsession_ (f77_int*);

// Corresponding F77 arguments for f77_upt_destructsession:
// integer, intent(inout) :: handler(DAC_handlerSize)
inline void f77_upt_destructsession (f77_int* handler)
{
  upt_destructsession_ (handler);
}


extern "C" void upt_fillbasicparameters_ (f77_int const*, f77_int const&, 
    f77_char const*, f77_char const*, f77_char const*, f77_char const*, f77_int 
    const&, f77_int const&, f77_int const&, f77_int const&, f77_int const&, 
    f77_int const&);

// Corresponding F77 arguments for f77_upt_fillbasicparameters:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: verbose_lev
// character(LST), intent(in) :: databasePath(1)
// character(LST), intent(in) :: workPath(1)
// character(MST), intent(in) :: gen_filename(1)
// character(MST), intent(in) :: gen_outname(1)
// integer, intent(in) :: max_n_n
// integer, intent(in) :: harrison_flag
// integer, intent(in) :: relat_flag
// integer, intent(in) :: potential_flag
// integer, intent(in) :: optmat_flag
// integer, intent(in) :: poldir
inline void f77_upt_fillbasicparameters (f77_int const* handler, f77_int const& 
    verbose_lev, f77_char const* databasePath, f77_char const* workPath, 
    f77_char const* gen_filename, f77_char const* gen_outname, f77_int const& 
    max_n_n, f77_int const& harrison_flag, f77_int const& relat_flag, f77_int 
    const& potential_flag, f77_int const& optmat_flag, f77_int const& poldir)
{
  upt_fillbasicparameters_ (handler, verbose_lev, databasePath, workPath, 
      gen_filename, gen_outname, max_n_n, harrison_flag, relat_flag, 
      potential_flag, optmat_flag, poldir);
}


extern "C" void upt_inituptight_ (f77_int const*);

// Corresponding F77 arguments for f77_upt_inituptight:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_upt_inituptight (f77_int const* handler)
{
  upt_inituptight_ (handler);
}


extern "C" void upt_destructuptight_ (f77_int const*);

// Corresponding F77 arguments for f77_upt_destructuptight:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_upt_destructuptight (f77_int const* handler)
{
  upt_destructuptight_ (handler);
}


extern "C" void upt_addpotential_ (f77_int const*, f77_int const&, f77_double 
    const*);

// Corresponding F77 arguments for f77_upt_addpotential:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nAtoms
// real(dp), intent(in) :: potential(nAtoms)
inline void f77_upt_addpotential (f77_int const* handler, f77_int const& 
    nAtoms, f77_double const* potential)
{
  upt_addpotential_ (handler, nAtoms, potential);
}


extern "C" void upt_createhamiltonian_ (f77_int const*);

// Corresponding F77 arguments for f77_upt_createhamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_upt_createhamiltonian (f77_int const* handler)
{
  upt_createhamiltonian_ (handler);
}


extern "C" void upt_addkpoints_ (f77_int const*, f77_int const&, f77_double 
    const*);

// Corresponding F77 arguments for f77_upt_addkpoints:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: num_k
// real(dp), intent(in) :: k_vec(3, num_k)
inline void f77_upt_addkpoints (f77_int const* handler, f77_int const& num_k, 
    f77_double const* k_vec)
{
  upt_addkpoints_ (handler, num_k, k_vec);
}


extern "C" void upt_lanczosdiag_ (f77_int const*, f77_int const&, f77_int 
    const&, f77_double const&, f77_double const&, f77_int const&, f77_int 
    const&, f77_int const&, f77_double const&, f77_double const&, f77_double 
    const&);

// Corresponding F77 arguments for f77_upt_lanczosdiag:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: n_vb
// integer, intent(in) :: n_cb
// real(dp), intent(in) :: guess_vb
// real(dp), intent(in) :: guess_cb
// integer, intent(in) :: min_iter
// integer, intent(in) :: long_iter
// integer, intent(in) :: max_iter
// real(dp), intent(in) :: fast_tol
// real(dp), intent(in) :: long_tol
// real(dp), intent(in) :: ort_tol
inline void f77_upt_lanczosdiag (f77_int const* handler, f77_int const& n_vb, 
    f77_int const& n_cb, f77_double const& guess_vb, f77_double const& 
    guess_cb, f77_int const& min_iter, f77_int const& long_iter, f77_int const& 
    max_iter, f77_double const& fast_tol, f77_double const& long_tol, 
    f77_double const& ort_tol)
{
  upt_lanczosdiag_ (handler, n_vb, n_cb, guess_vb, guess_cb, min_iter, 
      long_iter, max_iter, fast_tol, long_tol, ort_tol);
}


#endif

